# data loading

IMG_DIR_TRAINING: ""
IMG_DIR_VALIDATION: ""

ANNOTATIONS_FILE_TRAINING: ""
ANNOTATIONS_FILE_VALIDATION: ""


VALIDATION_RESULTS_DIR: ""

# model hyperparameters
NUM_EPOCHS: 30
BATCH_SIZE: 16
LEARNING_RATE: 0.001

#output
RESULTS_DIR: ""
